# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Genie - Cash Converters Design Guidelines
email: servicedesk@cashconverters.com
description: > # this means to ignore newlines until "baseurl:"
  Genie is the design system for Cash Converters, Australia's favourite place to buy and sell secondhand goods.
baseurl: "/Genie" # the subpath of your site, e.g. /blog
url: "http://cashconverters.github.io/Genie/" # the base hostname & protocol for your site
twitter_username: cashconvertersau
github_username:  cashconverters

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
